FROM debian:latest
# Install virtualenv
RUN apt-get update && apt-get install -y \
    python3-venv \
    cmake

# Create and activate a virtual environment
RUN python3 -m venv /opt/venv

# Upgrade pip in the virtual environment
RUN /opt/venv/bin/pip install --no-cache-dir --upgrade pip

# Install dependencies in the virtual environment
COPY requirements.txt .
RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

# Ensure the virtual environment is used by default
ENV PATH="/opt/venv/bin:$PATH"

# Command to run when the container starts
CMD ["python3", "find_BLE_devices.py"]